const item = (name: string, category: string, text: string, icon = 'square') => ({
  name,
  category,
  text,
  children: false,
  icon,
});
export const contentComponents = {
  label: item('라벨', '기본', '항목 이름', 'text'),
  link: item('링크', '기본', '자세히 보기', 'mouse-pointer'),
  icon: item('아이콘', '기본', '★'),
  image: item('이미지', '기본', '이미지 설명'),
  spacer: item('여백', '기본', ''),
  iconButton: item('아이콘 버튼', '동작', '추가'),
  toggleButton: item('토글 버튼', '동작', '즐겨찾기'),
  dropdownButton: item('드롭다운 버튼', '동작', '작업 선택'),
  fab: item('플로팅 버튼', '동작', '추가'),
  navbar: item('내비게이션 바', '탐색', '메인 메뉴'),
  menu: item('메뉴', '탐색', '메뉴'),
  tabs: item('탭', '탐색', '탭 콘텐츠'),
  breadcrumb: item('경로 표시', '탐색', '현재 위치'),
  pagination: item('페이지 번호', '탐색', '페이지'),
  stepper: item('단계 표시', '탐색', '진행 단계'),
  bottomNavigation: item('하단 탐색', '탐색', '하단 메뉴'),
  table: item('테이블', '데이터', '목록'),
  list: item('목록', '데이터', '목록'),
  keyValue: item('키와 값', '데이터', '상세 정보'),
  descriptionList: item('설명 목록', '데이터', '상세 정보'),
  badge: item('배지', '데이터', '새 소식'),
  chip: item('칩', '데이터', '디자인'),
  avatar: item('아바타', '데이터', '사용자'),
  accordion: item('아코디언', '데이터', '내용을 여기에 입력하세요.'),
  alert: item('알림', '피드백', '변경 사항이 저장되었습니다.'),
  progress: item('진행률', '피드백', '처리 진행률'),
  spinner: item('로딩 표시', '피드백', '불러오는 중'),
  skeleton: item('스켈레톤', '피드백', '콘텐츠를 불러오는 중'),
  emptyState: item('빈 상태', '피드백', '아직 항목이 없습니다.'),
  errorState: item('오류 상태', '피드백', '내용을 불러올 수 없습니다.'),
  jsonViewer: item('JSON 보기', '고급', '{\n  "title": "새 프로젝트",\n  "enabled": true\n}'),
} as const;
