const input = (name: string, text: string, icon = 'text-cursor-input') => ({
  name,
  text,
  category: '입력',
  children: false,
  icon,
});
export const formComponents = {
  password: input('비밀번호', '비밀번호'),
  number: input('숫자 입력', '수량'),
  search: input('검색창', '검색'),
  select: input('선택 목록', '옵션 선택'),
  multiSelect: input('다중 선택', '옵션 선택'),
  radio: input('라디오 그룹', '선택 항목'),
  switch: input('스위치', '알림 받기'),
  slider: input('슬라이더', '값 조정'),
  date: input('날짜 선택', '날짜'),
  time: input('시간 선택', '시간'),
  dateRange: input('날짜 범위', '기간'),
  fileUpload: input('파일 업로드', '파일'),
  otp: input('인증번호', '인증번호'),
  colorPicker: input('색상 선택', '색상'),
} as const;
export const inputTypes = ['input', 'textarea', ...Object.keys(formComponents), 'checkbox'];
export const optionTypes = [
  'select',
  'multiSelect',
  'radio',
  'dropdownButton',
  'menu',
  'navbar',
  'tabs',
  'breadcrumb',
  'stepper',
  'bottomNavigation',
  'list',
  'table',
  'keyValue',
  'descriptionList',
  'accordion',
];
